import React from 'react';
import service1 from './service1.module.css';

const Service1 = () => {
  const pic1 = 'https://cdn.homedit.com/wp-content/uploads/house-styles/english-cottage-architecture/English-country-style-architecture.jpg';
  const pic2 = 'https://img.freepik.com/free-photo/view-professional-handshake-business-people_23-2150917090.jpg?t=st=1722074469~exp=1722078069~hmac=631a73613abb44fee28c1962f16a7c0b99fa6590ff19ae1e8924612b3d594b38';
  return (
    <div>
      <div className={service1.bannerContainer}>
        <img src={pic1} className={service1.bannerImg} />
      </div>

      <hr className={service1.horizontal} />

      <div className={service1.topic}>
        <div className={service1.topicHeading}>
          Helping Clients Maximize Economic and Societal Value Through Expert Insights and Strategic Guidance in the Real Estate Sector
        </div>
        <div className={service1.topicPara}>
          <div>
            Investing in real estate isn’t just about owning property—it’s about driving substantial economic growth and creating valuable opportunities. In the U.S., real estate contributes a remarkable 13% to the GDP, reflecting its pivotal role in our economy. The sector supports over 4 million jobs, from construction to property management, making it a powerful engine for job creation and income generation.
          </div>
          <div>
            But real estate’s benefits extend beyond financial returns. Each new home built, for instance, supports about 3 local jobs and generates approximately $90,000 in community tax revenue. By investing wisely, you help transform communities, drive local business growth, and increase property values, contributing to vibrant, thriving neighborhoods.
          </div>
          <div>
            Moreover, real estate investments play a critical role in supporting public services through property taxes, which in the U.S. alone generated over $600 billion in 2022. Real estate is more than an investment—it's a strategic move for economic and community growth.
          </div>
        </div>

        <div className={` ${service1.stats} ${service1.gridContainer} `}>
          <div><span>~11%</span> <span>of global GDP</span> <span>is generated by real estate</span></div>
          <div className={service1.verticalLine}></div>
          <div><span>71</span> <span>million in employment</span> <span>generated as of 2024</span></div>
          <div className={service1.verticalLine}></div>
          <div><span>397.7</span> <span>trillion USD global wealth</span> <span>of the real estate market</span></div>
        </div>
      </div>

      <hr className={service1.horizontal} />

      <div className={service1.consultancySection}>
        <img src={pic2} className={service1.consultancyImg} alt="Real Estate Consultancy" />
        <div className={service1.consultancyContent}>
          <h2>Our Real Estate Investment Consultancy Services</h2>
          <p>
            At our consultancy firm, we provide comprehensive real estate investment services designed to help you maximize returns and achieve your financial goals. Our team of experienced professionals offers expert insights and strategic guidance tailored to your unique needs.
          </p>
          <p>
            We assist you in identifying high-potential investment opportunities, conducting thorough market analysis, and crafting personalized investment strategies. Our services also include risk assessment, portfolio management, and ongoing support to ensure your investments remain profitable and secure.
          </p>
          <p>
            Partner with us to unlock the full potential of your real estate investments and make informed decisions that drive long-term success.
          </p>
        </div>
      </div>

      <hr className={service1.horizontal} />

      <div className={service1.whyUsSection}>
        <h2>Why Work With Us?</h2>
        <p>
          Choosing our consultancy firm means partnering with a team dedicated to your success. We bring deep industry knowledge, a client-centric approach, and a proven track record of delivering exceptional results. Our commitment to integrity, transparency, and personalized service ensures that your investment journey is both rewarding and seamless.
        </p>
        <p>
          Let us guide you through the complexities of real estate investment, offering the insights and support you need to make confident, informed decisions. Together, we can turn your real estate ambitions into reality.
        </p>
      </div>

      <hr className={service1.horizontal} />

    </div>
  )
}

export default Service1;
