import React from 'react';
import productStyles from './product1.module.css';

const Product1 = () => {
  const pic1 = 'https://cdn.pixabay.com/photo/2016/06/07/16/48/notebook-1443404_960_720.jpg';
  const pic2 = 'https://cdn.pixabay.com/photo/2015/01/21/14/14/apple-606761_960_720.jpg';

  return (
    <div>
      <div className={productStyles.bannerContainer}>
        <img src={pic1} className={productStyles.bannerImg} alt="Web Development" />
      </div>

      <hr className={productStyles.horizontal} />

      <div className={productStyles.topic}>
        <div className={productStyles.topicHeading}>
          Building Cutting-Edge Websites for Enhanced Online Presence
        </div>
        <div className={productStyles.topicPara}>
          <div>
            Our website development services focus on creating high-quality, user-friendly websites that effectively communicate your brand and engage your audience. We utilize the latest technologies and design principles to ensure your website is both visually appealing and functionally robust.
          </div>
          <div>
            From responsive design to SEO optimization, we cover all aspects of web development to help you reach a wider audience and achieve your business goals. Our team works closely with you to understand your unique needs and deliver a customized solution that stands out in the digital landscape.
          </div>
          <div>
            By investing in professional website development, you not only enhance your online presence but also create a platform that supports your business growth and customer engagement.
          </div>
        </div>
        <div className={` ${productStyles.stats} ${productStyles.gridContainer} `}>
          <div><span>$29 Billion</span> <span>annual revenue</span> <span>generated by web development industry</span></div>
          <div className={productStyles.verticalLine}></div>
          <div><span>~12%</span> <span>average annual growth</span> <span>in web development market</span></div>
          <div className={productStyles.verticalLine}></div>
          <div><span>$2,000 - $10,000</span> <span>average cost</span> <span>for a business website</span></div>
        </div>
      </div>

      <hr className={productStyles.horizontal} />

      <div className={productStyles.developmentSection}>
        <img src={pic2} className={productStyles.developmentImg} alt="Web Development Process" />
        <div className={productStyles.developmentContent}>
          <h2>Our Web Development Process</h2>
          <p>
            Our development process is designed to ensure transparency, collaboration, and high-quality outcomes. We follow a structured approach that includes:
          </p>
          <p>
            <strong>1. Discovery and Planning:</strong> Understanding your business, goals, and target audience to create a strategic plan.
          </p>
          <p>
            <strong>2. Design and Prototyping:</strong> Crafting visually appealing and user-friendly designs that align with your brand.
          </p>
          <p>
            <strong>3. Development:</strong> Building your website using the latest technologies and best practices.
          </p>
          <p>
            <strong>4. Testing and Launch:</strong> Rigorous testing to ensure functionality, performance, and compatibility before going live.
          </p>
          <p>
            <strong>5. Maintenance and Support:</strong> Ongoing support to keep your website updated and running smoothly.
          </p>
        </div>
      </div>

      <hr className={productStyles.horizontal} />

      <div className={productStyles.featuresSection}>
        <h2>Features of Our Web Development Services</h2>
        <div className={productStyles.features}>
          <div><span>Responsive Design</span> <span>Ensures optimal viewing experience on all devices</span></div>
          <div className={productStyles.verticalLine}></div>
          <div><span>SEO Optimization</span> <span>Improves your search engine rankings</span></div>
          <div className={productStyles.verticalLine}></div>
          <div><span>E-commerce Integration</span> <span>Supports online sales and transactions</span></div>
        </div>
      </div>

      <hr className={productStyles.horizontal} />

      <div className={productStyles.whyUsSection}>
        <h2>Why Choose Our Web Development Services?</h2>
        <p>
          Partnering with us means working with a team dedicated to delivering exceptional results. We bring extensive industry knowledge, a client-focused approach, and a commitment to excellence. Our goal is to help you achieve a strong online presence that drives business success.
        </p>
        <p>
          Let us help you build a website that not only looks great but also performs seamlessly, offering a positive user experience that keeps your visitors engaged and coming back for more.
        </p>
      </div>

      <hr className={productStyles.horizontal} />

    </div>
  )
}

export default Product1;
